export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS"
export const CHANGE_HOT_RECOMMENDS = "CHANGE_HOT_RECOMMENDS"
export const CHANGE_NEW_ALBUMS = "CHANGE_NEW_ALBUMS"
export const CHANGE_UP_LIST = "CHAGNE_UP_LIST";
export const CHANGE_NEW_LIST = "CHANGE_NEW_LIST";
export const CHANGE_ORIGIN_LIST = "CHANGE_ORIGIN_LIST";
export const CHANGE_SETTLE_SONGER = "recommend/CHANGE_SETTLE_SONGER";


